UNITS_REQUIRING_NUMBERS = ["APARTMENT", "APT", "BUILDING", "BLDG", "DEPARTMENT","DEPT", "FLOOR", "FL", "HANGER", "HNGR", "KEY", "LOT", "PIER", "ROOM", "SLIP", "SPACE", "SPC", "STOP", "SUITE","STE", "TRAILER", "TRLR", "UNIT"]

UNITS_NOT_REQUIRING_NUMBERS = ["BASEMENT", "BSMT", "FRONT", "FRNT", "LOBBY", "LBBY", "LOT", "LOWER", "LOWR", "OFFICE", "OFC", "PENTHOUSE","PH", "REAR", "SIDE","UPPER","UPPR"]
